# Generated by Django 2.2.16 on 2022-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220730_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='default description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Картинка поста', null=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
